[functions]
    directory = "functions"
    included_files = ["./data/videos.json"]

[[redirects]]
    from = "/home"
    to = "/.netlify/functions/api/home"
    status = 200

[[redirects]]
    from = "/home/*"
    to = "/.netlify/functions/api/home/*"
    status = 200